### PR TITLE
add sentry integration for error logging

### PR DESCRIPTION
**Pull request by nathanstitt**
Based on https://docs.sentry.io/platforms/python/guides/flask/

This seems to be correct but it untested

### CODE REVIEW

**Review by Dantemss — COMMENTED** [review]
Not sure if it matters, but this is the private Sentry DSN which should probably be kept secret? I see tutor-js uses the public DSN.

**Review by reedstrm — CHANGES_REQUESTED** [review]
Hmm, the sentry DSN can be added to the validator config file, which then will make it available at current_app.config[keyname]. Then the specific value for the DSN can be added to the config file in the ansible deployment  - well, you'll have to add the config file, as well, turns out. Path to the config can be set in the environment as VALIDATOR_SETTINGS (or VALIDATOR_CONFIG) The only currently used setting is DATA_DIR (which can also be passed as an argument, and currently is, that's why there's no config file)

**Review by reedstrm — CHANGES_REQUESTED** [review]
Still not happy with putting OS specific configuration info in the code base. Anyone can install this app via pip, and end up filling our sentry w/ their logs. Hmm, in fact, I think test-runs will end up logging to sentry as well (some of which error on purpose) At minimum, add a line near the top of create_app:  `app.config['SENTRY_DSN'] =  os.environ.get('SENTRY_DSN')`, then guard the init of the interface s/ that being non-None. Add that hard coded URL to the already existing gunicorn unit-file template, over in validator-deployment.

**Review by reedstrm — APPROVED** [review]
Yup, paired w/ the deployment change, this looks good.

**Review by reedstrm — CHANGES_REQUESTED** [review]
oops, spoke too soon - fails travis, does this run locally?

**Review by reedstrm — APPROVED** [review]
Looks good now. We can ignore the coverage, or add a config file w/ a fake DSN to the testing path.

**Review by Dantemss — CHANGES_REQUESTED** [review]
This now needs the DSN changed since we switched to sentry.io

**Review by Dantemss — APPROVED** [review]
My bad, the DSN is actually in the deployment repo

**Pull request merged**
